added python modules

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -7,7 +7,7 @@ if [ "$(id -u)" != "0" ]; then
 fi
 
 PACKAGES="coreutils gnupg2"
-
+# install apt get packages
 for dep in $PACKAGES
 do
 	echo "\033[47;34m>>> installing package $dep\033[0m"
@@ -15,6 +15,11 @@ do
 done
 
 
+PYLIBS="gnupg qrcode docopt"
 # install python dependency
-pip install gnupg
+for dep in $PYLIBS
+do
+	echo "\033[47;34m>>> installing python library $dep\033[0m"
+	pip install $dep || fatal "unable to install $dep"
+done
 
